// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(missing_docs)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::use_self)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    use libbpf_rs::ObjectBuilder;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(&DATA);
        builder
            .name("api_sentinel_bpf")
            .map("events", false)
            .map(".rodata.str1.1", false)
            .prog("api_sentinel");
        builder.build()
    }
    pub struct OpenApiSentinelMaps<'obj> {
        pub events: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_str1_1: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenApiSentinelMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut rodata_str1_1 = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    ".rodata.str1.1" => rodata_str1_1 = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                rodata_str1_1: rodata_str1_1.expect("map `rodata_str1_1` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ApiSentinelMaps<'obj> {
        pub events: libbpf_rs::MapMut<'obj>,
        pub rodata_str1_1: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ApiSentinelMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut rodata_str1_1 = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    ".rodata.str1.1" => rodata_str1_1 = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                rodata_str1_1: rodata_str1_1.expect("map `rodata_str1_1` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenApiSentinelProgs<'obj> {
        pub api_sentinel: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenApiSentinelProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut api_sentinel = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "api_sentinel" => api_sentinel = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                api_sentinel: api_sentinel.expect("prog `api_sentinel` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ApiSentinelProgs<'obj> {
        pub api_sentinel: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ApiSentinelProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenApiSentinelProgs<'obj>) -> Self {
            Self {
                api_sentinel: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.api_sentinel.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct ApiSentinelSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> ApiSentinelSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenApiSentinelSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenApiSentinelSkel {
                maps: unsafe { OpenApiSentinelMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenApiSentinelProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for ApiSentinelSkelBuilder {
        type Output = OpenApiSentinelSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenApiSentinelSkel<'obj>> {
            // Only produce a pointer to our custom open opts object
            // if customizations have been made. This works around a
            // bug in older versions of libbpf.
            let opts = if self.obj_builder.ne(&ObjectBuilder::default()) {
                self.obj_builder.as_libbpf_object().as_ptr().cast_const()
            } else {
                std::ptr::null()
            };
            self.open_opts_impl(opts, object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenApiSentinelSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 16777216],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub r15: u64,
            pub r14: u64,
            pub r13: u64,
            pub r12: u64,
            pub bp: u64,
            pub bx: u64,
            pub r11: u64,
            pub r10: u64,
            pub r9: u64,
            pub r8: u64,
            pub ax: u64,
            pub cx: u64,
            pub dx: u64,
            pub si: u64,
            pub di: u64,
            pub orig_ax: u64,
            pub ip: u64,
            pub __anon_pt_regs_1: __anon_pt_regs_1,
            pub flags: u64,
            pub sp: u64,
            pub __anon_pt_regs_2: __anon_pt_regs_2,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_1 {
            pub cs: u16,
            pub csx: u64,
            pub fred_cs: fred_cs,
        }
        impl std::fmt::Debug for __anon_pt_regs_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_1 {
            fn default() -> Self {
                Self { cs: u16::default() }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_2 {
            pub ss: u16,
            pub ssx: u64,
            pub fred_ss: fred_ss,
        }
        impl std::fmt::Debug for __anon_pt_regs_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_2 {
            fn default() -> Self {
                Self { ss: u16::default() }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct fred_cs {
            pub __pad_0: [u8; 8],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct fred_ss {
            pub __pad_0: [u8; 8],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct msghdr {
            pub msg_name: *mut std::ffi::c_void,
            pub msg_namelen: i32,
            pub msg_inq: i32,
            pub msg_iter: iov_iter,
            pub __anon_msghdr_2: __anon_msghdr_2,
            pub __pad_64: [u8; 4],
            pub msg_flags: u32,
            pub msg_controllen: u64,
            pub msg_iocb: *mut std::ffi::c_void,
            pub msg_ubuf: *mut std::ffi::c_void,
            pub sg_from_iter: *mut std::ffi::c_void,
        }
        impl Default for msghdr {
            fn default() -> Self {
                Self {
                    msg_name: std::ptr::null_mut(),
                    msg_namelen: i32::default(),
                    msg_inq: i32::default(),
                    msg_iter: iov_iter::default(),
                    __anon_msghdr_2: __anon_msghdr_2::default(),
                    __pad_64: [u8::default(); 4],
                    msg_flags: u32::default(),
                    msg_controllen: u64::default(),
                    msg_iocb: std::ptr::null_mut(),
                    msg_ubuf: std::ptr::null_mut(),
                    sg_from_iter: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct iov_iter {
            pub iter_type: u8,
            pub nofault: std::mem::MaybeUninit<bool>,
            pub data_source: std::mem::MaybeUninit<bool>,
            pub __pad_3: [u8; 5],
            pub iov_offset: u64,
            pub __anon_iov_iter_1: __anon_iov_iter_1,
            pub __anon_iov_iter_2: __anon_iov_iter_2,
        }
        impl Default for iov_iter {
            fn default() -> Self {
                Self {
                    iter_type: u8::default(),
                    nofault: std::mem::MaybeUninit::new(bool::default()),
                    data_source: std::mem::MaybeUninit::new(bool::default()),
                    __pad_3: [u8::default(); 5],
                    iov_offset: u64::default(),
                    __anon_iov_iter_1: __anon_iov_iter_1::default(),
                    __anon_iov_iter_2: __anon_iov_iter_2::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_msghdr_2 {
            pub msg_control: *mut std::ffi::c_void,
            pub msg_control_user: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_msghdr_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_msghdr_2 {
            fn default() -> Self {
                Self {
                    msg_control: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_iov_iter_1 {
            pub __ubuf_iovec: iovec,
            pub __anon_iov_iter_4: __anon_iov_iter_4,
        }
        impl std::fmt::Debug for __anon_iov_iter_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_iov_iter_1 {
            fn default() -> Self {
                Self {
                    __ubuf_iovec: iovec::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_iov_iter_2 {
            pub nr_segs: u64,
            pub folioq_slot: u8,
            pub xarray_start: i64,
        }
        impl std::fmt::Debug for __anon_iov_iter_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_iov_iter_2 {
            fn default() -> Self {
                Self {
                    nr_segs: u64::default(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct iovec {
            pub iov_base: *mut std::ffi::c_void,
            pub iov_len: u64,
        }
        impl Default for iovec {
            fn default() -> Self {
                Self {
                    iov_base: std::ptr::null_mut(),
                    iov_len: u64::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_iov_iter_4 {
            pub __anon_iov_iter_5: __anon_iov_iter_5,
            pub count: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_iov_iter_5 {
            pub __iov: *mut iovec,
            pub kvec: *mut std::ffi::c_void,
            pub bvec: *mut std::ffi::c_void,
            pub folioq: *mut std::ffi::c_void,
            pub xarray: *mut std::ffi::c_void,
            pub ubuf: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_iov_iter_5 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_iov_iter_5 {
            fn default() -> Self {
                Self {
                    __iov: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct sk_buff {
            pub __anon_sk_buff_1: __anon_sk_buff_1,
            pub sk: *mut std::ffi::c_void,
            pub __anon_sk_buff_2: __anon_sk_buff_2,
            pub cb: [i8; 48],
            pub __anon_sk_buff_3: __anon_sk_buff_3,
            pub _nfct: u64,
            pub len: u32,
            pub data_len: u32,
            pub mac_len: u16,
            pub hdr_len: u16,
            pub queue_mapping: u16,
            pub __cloned_offset: [u8; 0],
            pub __pad_126: [u8; 1],
            pub active_extensions: u8,
            pub __anon_sk_buff_4: __anon_sk_buff_4,
            pub tail: u32,
            pub end: u32,
            pub __pad_196: [u8; 4],
            pub head: *mut u8,
            pub data: *mut u8,
            pub truesize: u32,
            pub users: refcount_struct,
            pub extensions: *mut std::ffi::c_void,
        }
        impl Default for sk_buff {
            fn default() -> Self {
                Self {
                    __anon_sk_buff_1: __anon_sk_buff_1::default(),
                    sk: std::ptr::null_mut(),
                    __anon_sk_buff_2: __anon_sk_buff_2::default(),
                    cb: [i8::default(); 48],
                    __anon_sk_buff_3: __anon_sk_buff_3::default(),
                    _nfct: u64::default(),
                    len: u32::default(),
                    data_len: u32::default(),
                    mac_len: u16::default(),
                    hdr_len: u16::default(),
                    queue_mapping: u16::default(),
                    __cloned_offset: [u8::default(); 0],
                    __pad_126: [u8::default(); 1],
                    active_extensions: u8::default(),
                    __anon_sk_buff_4: __anon_sk_buff_4::default(),
                    tail: u32::default(),
                    end: u32::default(),
                    __pad_196: [u8::default(); 4],
                    head: std::ptr::null_mut(),
                    data: std::ptr::null_mut(),
                    truesize: u32::default(),
                    users: refcount_struct::default(),
                    extensions: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_1 {
            pub __anon_sk_buff_6: __anon_sk_buff_6,
            pub rbnode: rb_node,
            pub list: list_head,
            pub ll_node: llist_node,
        }
        impl std::fmt::Debug for __anon_sk_buff_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_1 {
            fn default() -> Self {
                Self {
                    __anon_sk_buff_6: __anon_sk_buff_6::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_2 {
            pub tstamp: i64,
            pub skb_mstamp_ns: u64,
        }
        impl std::fmt::Debug for __anon_sk_buff_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_2 {
            fn default() -> Self {
                Self {
                    tstamp: i64::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_3 {
            pub __anon_sk_buff_10: __anon_sk_buff_10,
            pub tcp_tsorted_anchor: list_head,
            pub _sk_redir: u64,
        }
        impl std::fmt::Debug for __anon_sk_buff_3 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_3 {
            fn default() -> Self {
                Self {
                    __anon_sk_buff_10: __anon_sk_buff_10::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_4 {
            pub __anon_sk_buff_11: __anon_sk_buff_11,
            pub headers: __anon_sk_buff_11,
        }
        impl std::fmt::Debug for __anon_sk_buff_4 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_4 {
            fn default() -> Self {
                Self {
                    __anon_sk_buff_11: __anon_sk_buff_11::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct refcount_struct {
            pub refs: __anon_refcount_struct_1,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_sk_buff_6 {
            pub next: *mut sk_buff,
            pub prev: *mut sk_buff,
            pub __anon_sk_buff_12: __anon_sk_buff_12,
        }
        impl Default for __anon_sk_buff_6 {
            fn default() -> Self {
                Self {
                    next: std::ptr::null_mut(),
                    prev: std::ptr::null_mut(),
                    __anon_sk_buff_12: __anon_sk_buff_12::default(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rb_node {
            pub __rb_parent_color: u64,
            pub rb_right: *mut rb_node,
            pub rb_left: *mut rb_node,
        }
        impl Default for rb_node {
            fn default() -> Self {
                Self {
                    __rb_parent_color: u64::default(),
                    rb_right: std::ptr::null_mut(),
                    rb_left: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct list_head {
            pub next: *mut list_head,
            pub prev: *mut list_head,
        }
        impl Default for list_head {
            fn default() -> Self {
                Self {
                    next: std::ptr::null_mut(),
                    prev: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct llist_node {
            pub next: *mut llist_node,
        }
        impl Default for llist_node {
            fn default() -> Self {
                Self {
                    next: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_sk_buff_10 {
            pub _skb_refdst: u64,
            pub destructor: *mut std::ffi::c_void,
        }
        impl Default for __anon_sk_buff_10 {
            fn default() -> Self {
                Self {
                    _skb_refdst: u64::default(),
                    destructor: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_sk_buff_11 {
            pub __pkt_type_offset: [u8; 0],
            pub __pad_0: [u8; 1],
            pub __mono_tc_offset: [u8; 0],
            pub __pad_1: [u8; 5],
            pub tc_index: u16,
            pub alloc_cpu: u16,
            pub __anon_sk_buff_13: __anon_sk_buff_13,
            pub priority: u32,
            pub skb_iif: i32,
            pub hash: u32,
            pub __anon_sk_buff_14: __anon_sk_buff_14,
            pub __anon_sk_buff_15: __anon_sk_buff_15,
            pub secmark: u32,
            pub __anon_sk_buff_16: __anon_sk_buff_16,
            pub __anon_sk_buff_17: __anon_sk_buff_17,
            pub inner_transport_header: u16,
            pub inner_network_header: u16,
            pub inner_mac_header: u16,
            pub protocol: u16,
            pub transport_header: u16,
            pub network_header: u16,
            pub mac_header: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_refcount_struct_1 {
            pub counter: i32,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_12 {
            pub dev: *mut std::ffi::c_void,
            pub dev_scratch: u64,
        }
        impl std::fmt::Debug for __anon_sk_buff_12 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_12 {
            fn default() -> Self {
                Self {
                    dev: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_13 {
            pub csum: u32,
            pub __anon_sk_buff_18: __anon_sk_buff_18,
        }
        impl std::fmt::Debug for __anon_sk_buff_13 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_13 {
            fn default() -> Self {
                Self {
                    csum: u32::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_14 {
            pub vlan_all: u32,
            pub __anon_sk_buff_19: __anon_sk_buff_19,
        }
        impl std::fmt::Debug for __anon_sk_buff_14 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_14 {
            fn default() -> Self {
                Self {
                    vlan_all: u32::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_15 {
            pub napi_id: u32,
            pub sender_cpu: u32,
        }
        impl std::fmt::Debug for __anon_sk_buff_15 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_15 {
            fn default() -> Self {
                Self {
                    napi_id: u32::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_16 {
            pub mark: u32,
            pub reserved_tailroom: u32,
        }
        impl std::fmt::Debug for __anon_sk_buff_16 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_16 {
            fn default() -> Self {
                Self {
                    mark: u32::default(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_sk_buff_17 {
            pub inner_protocol: u16,
            pub inner_ipproto: u8,
        }
        impl std::fmt::Debug for __anon_sk_buff_17 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_sk_buff_17 {
            fn default() -> Self {
                Self {
                    inner_protocol: u16::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_sk_buff_18 {
            pub csum_start: u16,
            pub csum_offset: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_sk_buff_19 {
            pub vlan_proto: u16,
            pub vlan_tci: u16,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub events: __anon_1,
        }
    }
    pub struct OpenApiSentinelSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenApiSentinelMaps<'obj>,
        pub progs: OpenApiSentinelProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenApiSentinelSkel<'obj> {
        type Output = ApiSentinelSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<ApiSentinelSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(ApiSentinelSkel {
                maps: unsafe { ApiSentinelMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: ApiSentinelProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: ApiSentinelLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct ApiSentinelLinks {
        pub api_sentinel: Option<libbpf_rs::Link>,
    }
    pub struct ApiSentinelSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: ApiSentinelMaps<'obj>,
        pub progs: ApiSentinelProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: ApiSentinelLinks,
    }

    unsafe impl Send for ApiSentinelSkel<'_> {}
    unsafe impl Sync for ApiSentinelSkel<'_> {}

    impl<'obj> Skel<'obj> for ApiSentinelSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = ApiSentinelLinks {
                api_sentinel: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl ApiSentinelSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    #[unsafe(link_section = ".bpf.objs")]
    static DATA: [u8; 9808] = [
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 107, 112, 114, 111, 98, 101, 47, 116, 99, 112, 95, 115, 101, 110, 100, 109, 115,
        103, 95, 108, 111, 99, 107, 101, 100, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97,
        112, 115, 0, 46, 114, 111, 100, 97, 116, 97, 46, 115, 116, 114, 49, 46, 49, 0, 97, 112,
        105, 95, 115, 101, 110, 116, 105, 110, 101, 108, 46, 98, 112, 102, 46, 99, 0, 97, 112, 105,
        95, 115, 101, 110, 116, 105, 110, 101, 108, 0, 101, 118, 101, 110, 116, 115, 0, 76, 73, 67,
        69, 78, 83, 69, 0, 46, 114, 101, 108, 107, 112, 114, 111, 98, 101, 47, 116, 99, 112, 95,
        115, 101, 110, 100, 109, 115, 103, 95, 108, 111, 99, 107, 101, 100, 0, 46, 66, 84, 70, 0,
        46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 0, 0, 0, 18, 0,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 4, 0, 0, 0, 0, 0, 0, 104, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 111, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 121, 22, 104, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0,
        0, 240, 255, 255, 255, 180, 2, 0, 0, 16, 0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 113, 161, 241,
        255, 0, 0, 0, 0, 100, 1, 0, 0, 8, 0, 0, 0, 113, 162, 240, 255, 0, 0, 0, 0, 76, 33, 0, 0, 0,
        0, 0, 0, 113, 162, 242, 255, 0, 0, 0, 0, 100, 2, 0, 0, 16, 0, 0, 0, 113, 163, 243, 255, 0,
        0, 0, 0, 100, 3, 0, 0, 24, 0, 0, 0, 76, 35, 0, 0, 0, 0, 0, 0, 76, 19, 0, 0, 0, 0, 0, 0, 22,
        3, 2, 0, 117, 118, 105, 99, 180, 1, 0, 0, 1, 0, 0, 0, 5, 0, 8, 0, 0, 0, 0, 0, 113, 161,
        245, 255, 0, 0, 0, 0, 100, 1, 0, 0, 8, 0, 0, 0, 113, 162, 244, 255, 0, 0, 0, 0, 76, 33, 0,
        0, 0, 0, 0, 0, 86, 1, 249, 255, 111, 114, 0, 0, 180, 1, 0, 0, 0, 0, 0, 0, 113, 162, 246,
        255, 0, 0, 0, 0, 86, 2, 246, 255, 110, 0, 0, 0, 86, 1, 111, 0, 0, 0, 0, 0, 183, 8, 0, 0, 0,
        0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 32, 1, 0, 0, 183,
        3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 7, 0, 0, 0, 0, 0, 0, 21, 7, 103, 0,
        0, 0, 0, 0, 133, 0, 0, 0, 5, 0, 0, 0, 123, 7, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0,
        119, 0, 0, 0, 32, 0, 0, 0, 99, 7, 8, 0, 0, 0, 0, 0, 113, 161, 247, 255, 0, 0, 0, 0, 115,
        23, 23, 0, 0, 0, 0, 0, 113, 161, 246, 255, 0, 0, 0, 0, 115, 23, 22, 0, 0, 0, 0, 0, 113,
        161, 245, 255, 0, 0, 0, 0, 115, 23, 21, 0, 0, 0, 0, 0, 113, 161, 244, 255, 0, 0, 0, 0, 115,
        23, 20, 0, 0, 0, 0, 0, 113, 161, 243, 255, 0, 0, 0, 0, 115, 23, 19, 0, 0, 0, 0, 0, 113,
        161, 242, 255, 0, 0, 0, 0, 115, 23, 18, 0, 0, 0, 0, 0, 113, 161, 241, 255, 0, 0, 0, 0, 115,
        23, 17, 0, 0, 0, 0, 0, 113, 161, 240, 255, 0, 0, 0, 0, 115, 23, 16, 0, 0, 0, 0, 0, 113,
        161, 255, 255, 0, 0, 0, 0, 115, 23, 31, 0, 0, 0, 0, 0, 113, 161, 254, 255, 0, 0, 0, 0, 115,
        23, 30, 0, 0, 0, 0, 0, 113, 161, 253, 255, 0, 0, 0, 0, 115, 23, 29, 0, 0, 0, 0, 0, 113,
        161, 252, 255, 0, 0, 0, 0, 115, 23, 28, 0, 0, 0, 0, 0, 113, 161, 251, 255, 0, 0, 0, 0, 115,
        23, 27, 0, 0, 0, 0, 0, 113, 161, 250, 255, 0, 0, 0, 0, 115, 23, 26, 0, 0, 0, 0, 0, 113,
        161, 249, 255, 0, 0, 0, 0, 115, 23, 25, 0, 0, 0, 0, 0, 113, 161, 248, 255, 0, 0, 0, 0, 115,
        23, 24, 0, 0, 0, 0, 0, 123, 135, 32, 0, 0, 0, 0, 0, 123, 135, 40, 0, 0, 0, 0, 0, 123, 135,
        48, 0, 0, 0, 0, 0, 123, 135, 56, 0, 0, 0, 0, 0, 123, 135, 64, 0, 0, 0, 0, 0, 123, 135, 72,
        0, 0, 0, 0, 0, 123, 135, 80, 0, 0, 0, 0, 0, 123, 135, 88, 0, 0, 0, 0, 0, 123, 135, 96, 0,
        0, 0, 0, 0, 123, 135, 104, 0, 0, 0, 0, 0, 123, 135, 112, 0, 0, 0, 0, 0, 123, 135, 120, 0,
        0, 0, 0, 0, 123, 135, 128, 0, 0, 0, 0, 0, 123, 135, 136, 0, 0, 0, 0, 0, 123, 135, 144, 0,
        0, 0, 0, 0, 123, 135, 152, 0, 0, 0, 0, 0, 123, 135, 160, 0, 0, 0, 0, 0, 123, 135, 168, 0,
        0, 0, 0, 0, 123, 135, 176, 0, 0, 0, 0, 0, 123, 135, 184, 0, 0, 0, 0, 0, 123, 135, 192, 0,
        0, 0, 0, 0, 123, 135, 200, 0, 0, 0, 0, 0, 123, 135, 208, 0, 0, 0, 0, 0, 123, 135, 216, 0,
        0, 0, 0, 0, 123, 135, 224, 0, 0, 0, 0, 0, 123, 135, 232, 0, 0, 0, 0, 0, 123, 135, 240, 0,
        0, 0, 0, 0, 123, 135, 248, 0, 0, 0, 0, 0, 123, 135, 0, 1, 0, 0, 0, 0, 123, 135, 8, 1, 0, 0,
        0, 0, 123, 135, 16, 1, 0, 0, 0, 0, 123, 135, 24, 1, 0, 0, 0, 0, 180, 1, 0, 0, 0, 0, 0, 0,
        99, 23, 12, 0, 0, 0, 0, 0, 123, 138, 232, 255, 0, 0, 0, 0, 123, 138, 224, 255, 0, 0, 0, 0,
        123, 138, 216, 255, 0, 0, 0, 0, 123, 138, 208, 255, 0, 0, 0, 0, 123, 138, 200, 255, 0, 0,
        0, 0, 183, 1, 0, 0, 16, 0, 0, 0, 15, 22, 0, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7,
        1, 0, 0, 200, 255, 255, 255, 180, 2, 0, 0, 40, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 133, 0,
        0, 0, 113, 0, 0, 0, 85, 0, 16, 0, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 200,
        255, 255, 255, 121, 49, 16, 0, 0, 0, 0, 0, 21, 1, 12, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0,
        0, 0, 7, 1, 0, 0, 200, 255, 255, 255, 121, 18, 24, 0, 0, 0, 0, 0, 21, 2, 8, 0, 0, 0, 0, 0,
        121, 18, 24, 0, 0, 0, 0, 0, 84, 2, 0, 0, 255, 0, 0, 0, 22, 2, 5, 0, 0, 0, 0, 0, 191, 113,
        0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 32, 0, 0, 0, 99, 39, 12, 0, 0, 0, 0, 0, 121, 51, 16, 0, 0, 0,
        0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 132, 0, 0, 0, 180, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, 118, 105, 99, 111, 114,
        110, 0, 224, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0,
        0, 0, 0, 100, 15, 0, 0, 100, 15, 0, 0, 178, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0,
        0, 0, 4, 0, 0, 0, 27, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0,
        0, 5, 0, 0, 0, 64, 0, 0, 0, 42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 10, 0, 0, 0, 49, 0, 0, 0, 21, 0, 0, 4, 168, 0, 0, 0, 57, 0, 0, 0, 11, 0, 0, 0,
        0, 0, 0, 0, 61, 0, 0, 0, 11, 0, 0, 0, 64, 0, 0, 0, 65, 0, 0, 0, 11, 0, 0, 0, 128, 0, 0, 0,
        69, 0, 0, 0, 11, 0, 0, 0, 192, 0, 0, 0, 73, 0, 0, 0, 11, 0, 0, 0, 0, 1, 0, 0, 76, 0, 0, 0,
        11, 0, 0, 0, 64, 1, 0, 0, 79, 0, 0, 0, 11, 0, 0, 0, 128, 1, 0, 0, 83, 0, 0, 0, 11, 0, 0, 0,
        192, 1, 0, 0, 87, 0, 0, 0, 11, 0, 0, 0, 0, 2, 0, 0, 90, 0, 0, 0, 11, 0, 0, 0, 64, 2, 0, 0,
        93, 0, 0, 0, 11, 0, 0, 0, 128, 2, 0, 0, 96, 0, 0, 0, 11, 0, 0, 0, 192, 2, 0, 0, 99, 0, 0,
        0, 11, 0, 0, 0, 0, 3, 0, 0, 102, 0, 0, 0, 11, 0, 0, 0, 64, 3, 0, 0, 105, 0, 0, 0, 11, 0, 0,
        0, 128, 3, 0, 0, 108, 0, 0, 0, 11, 0, 0, 0, 192, 3, 0, 0, 116, 0, 0, 0, 11, 0, 0, 0, 0, 4,
        0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 64, 4, 0, 0, 119, 0, 0, 0, 11, 0, 0, 0, 128, 4, 0, 0, 125,
        0, 0, 0, 11, 0, 0, 0, 192, 4, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 5, 0, 0, 128, 0, 0, 0, 0,
        0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 5, 8, 0, 0, 0, 142, 0, 0, 0, 13, 0,
        0, 0, 0, 0, 0, 0, 145, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 19, 0, 0, 0, 0, 0,
        0, 0, 157, 0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 161, 0, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 167, 0,
        0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 182, 0, 0, 0, 0, 0, 0, 8, 17, 0, 0, 0, 186, 0,
        0, 0, 0, 0, 0, 8, 18, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 149, 0,
        0, 0, 3, 0, 0, 132, 8, 0, 0, 0, 142, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 16, 211, 0, 0, 0, 16,
        0, 0, 0, 16, 0, 0, 2, 214, 0, 0, 0, 16, 0, 0, 0, 18, 0, 0, 1, 0, 0, 0, 0, 3, 0, 0, 5, 8, 0,
        0, 0, 218, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 221, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 225, 0,
        0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 10, 0, 0, 132, 8, 0, 0, 0, 218, 0, 0, 0, 16,
        0, 0, 0, 0, 0, 0, 16, 233, 0, 0, 0, 16, 0, 0, 0, 16, 0, 0, 1, 237, 0, 0, 0, 16, 0, 0, 0,
        17, 0, 0, 1, 245, 0, 0, 0, 16, 0, 0, 0, 18, 0, 0, 1, 249, 0, 0, 0, 16, 0, 0, 0, 32, 0, 0,
        8, 25, 0, 0, 0, 16, 0, 0, 0, 48, 0, 0, 4, 0, 1, 0, 0, 16, 0, 0, 0, 56, 0, 0, 1, 8, 1, 0, 0,
        16, 0, 0, 0, 57, 0, 0, 1, 10, 1, 0, 0, 16, 0, 0, 0, 58, 0, 0, 1, 17, 1, 0, 0, 16, 0, 0, 0,
        60, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 25, 1, 0, 0, 9, 0, 0, 0, 29, 1, 0, 0, 1,
        0, 0, 12, 22, 0, 0, 0, 42, 1, 0, 0, 12, 0, 0, 132, 104, 0, 0, 0, 49, 1, 0, 0, 25, 0, 0, 0,
        0, 0, 0, 0, 58, 1, 0, 0, 2, 0, 0, 0, 64, 0, 0, 0, 70, 1, 0, 0, 2, 0, 0, 0, 96, 0, 0, 0, 78,
        1, 0, 0, 26, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 52, 0, 0, 0, 192, 1, 0, 0, 87, 1, 0, 0, 30,
        0, 0, 0, 0, 2, 0, 1, 107, 1, 0, 0, 30, 0, 0, 0, 1, 2, 0, 1, 119, 1, 0, 0, 53, 0, 0, 0, 32,
        2, 0, 0, 129, 1, 0, 0, 33, 0, 0, 0, 64, 2, 0, 0, 144, 1, 0, 0, 54, 0, 0, 0, 128, 2, 0, 0,
        153, 1, 0, 0, 55, 0, 0, 0, 192, 2, 0, 0, 162, 1, 0, 0, 56, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 0, 0, 0, 0, 175, 1, 0, 0, 6, 0, 0, 4, 40, 0, 0, 0, 184, 1, 0, 0, 27, 0, 0, 0,
        0, 0, 0, 0, 194, 1, 0, 0, 30, 0, 0, 0, 8, 0, 0, 0, 202, 1, 0, 0, 30, 0, 0, 0, 16, 0, 0, 0,
        214, 1, 0, 0, 32, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0,
        48, 0, 0, 0, 0, 1, 0, 0, 225, 1, 0, 0, 0, 0, 0, 8, 28, 0, 0, 0, 228, 1, 0, 0, 0, 0, 0, 8,
        29, 0, 0, 0, 233, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 247, 1, 0, 0, 0, 0, 0, 8,
        31, 0, 0, 0, 252, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 4, 2, 2, 0, 0, 0, 0, 0, 8, 33,
        0, 0, 0, 9, 2, 0, 0, 0, 0, 0, 8, 34, 0, 0, 0, 25, 2, 0, 0, 0, 0, 0, 8, 11, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 16, 0, 0, 0, 42, 2, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 0,
        0, 0, 0, 0, 0, 55, 2, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 61, 2, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0,
        70, 2, 0, 0, 33, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 0, 0, 0, 0, 38,
        0, 0, 0, 0, 0, 0, 0, 78, 2, 0, 0, 32, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 5, 8, 0,
        0, 0, 84, 2, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 90, 2, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 95, 2, 0,
        0, 43, 0, 0, 0, 0, 0, 0, 0, 100, 2, 0, 0, 45, 0, 0, 0, 0, 0, 0, 0, 107, 2, 0, 0, 47, 0, 0,
        0, 0, 0, 0, 0, 114, 2, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 40, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 10, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 42, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 10, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 108,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 114, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 111, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 5, 8, 0, 0, 0, 119, 2, 0, 0, 11, 0, 0,
        0, 0, 0, 0, 0, 127, 2, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 139, 2, 0, 0, 49, 0, 0, 0, 0, 0, 0,
        0, 152, 2, 0, 0, 0, 0, 0, 8, 50, 0, 0, 0, 159, 2, 0, 0, 0, 0, 0, 8, 51, 0, 0, 0, 175, 2, 0,
        0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 5, 8, 0, 0, 0, 185, 2, 0, 0,
        25, 0, 0, 0, 0, 0, 0, 0, 197, 2, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 214, 2, 0, 0, 0, 0, 0, 1,
        4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 110, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 113,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 57, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 13, 2, 0, 0, 0, 0, 0, 0,
        0, 58, 0, 0, 0, 0, 0, 0, 0, 102, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        59, 0, 0, 0, 227, 2, 0, 0, 28, 0, 0, 132, 232, 0, 0, 0, 0, 0, 0, 0, 60, 0, 0, 0, 0, 0, 0,
        0, 235, 2, 0, 0, 70, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0, 0, 0, 1, 0, 0, 238, 2, 0,
        0, 76, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 0, 77, 0, 0, 0, 192, 2, 0, 0, 241, 2, 0, 0, 11, 0, 0,
        0, 64, 3, 0, 0, 247, 2, 0, 0, 53, 0, 0, 0, 128, 3, 0, 0, 251, 2, 0, 0, 53, 0, 0, 0, 160, 3,
        0, 0, 4, 3, 0, 0, 14, 0, 0, 0, 192, 3, 0, 0, 12, 3, 0, 0, 14, 0, 0, 0, 208, 3, 0, 0, 20, 3,
        0, 0, 14, 0, 0, 0, 224, 3, 0, 0, 34, 3, 0, 0, 81, 0, 0, 0, 240, 3, 0, 0, 50, 3, 0, 0, 28,
        0, 0, 0, 240, 3, 0, 1, 57, 3, 0, 0, 28, 0, 0, 0, 241, 3, 0, 1, 63, 3, 0, 0, 28, 0, 0, 0,
        242, 3, 0, 2, 70, 3, 0, 0, 28, 0, 0, 0, 244, 3, 0, 1, 77, 3, 0, 0, 28, 0, 0, 0, 245, 3, 0,
        1, 87, 3, 0, 0, 28, 0, 0, 0, 246, 3, 0, 1, 98, 3, 0, 0, 28, 0, 0, 0, 247, 3, 0, 1, 109, 3,
        0, 0, 28, 0, 0, 0, 248, 3, 0, 0, 0, 0, 0, 0, 82, 0, 0, 0, 0, 4, 0, 0, 127, 3, 0, 0, 95, 0,
        0, 0, 224, 5, 0, 0, 132, 3, 0, 0, 95, 0, 0, 0, 0, 6, 0, 0, 136, 3, 0, 0, 96, 0, 0, 0, 64,
        6, 0, 0, 141, 3, 0, 0, 96, 0, 0, 0, 128, 6, 0, 0, 146, 3, 0, 0, 53, 0, 0, 0, 192, 6, 0, 0,
        155, 3, 0, 0, 97, 0, 0, 0, 224, 6, 0, 0, 161, 3, 0, 0, 101, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 5, 24, 0, 0, 0, 0, 0, 0, 0, 61, 0, 0, 0, 0, 0, 0, 0, 172, 3, 0, 0, 64, 0, 0, 0,
        0, 0, 0, 0, 179, 3, 0, 0, 66, 0, 0, 0, 0, 0, 0, 0, 184, 3, 0, 0, 68, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 0, 4, 24, 0, 0, 0, 192, 3, 0, 0, 58, 0, 0, 0, 0, 0, 0, 0, 197, 3, 0, 0,
        58, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 62, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 8,
        0, 0, 0, 202, 3, 0, 0, 63, 0, 0, 0, 0, 0, 0, 0, 206, 3, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 109, 0, 0, 0, 218, 3, 0, 0, 3, 0, 0, 4, 24, 0, 0, 0, 226, 3, 0, 0, 11,
        0, 0, 0, 0, 0, 0, 0, 244, 3, 0, 0, 65, 0, 0, 0, 64, 0, 0, 0, 253, 3, 0, 0, 65, 0, 0, 0,
        128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 64, 0, 0, 0, 5, 4, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0,
        192, 3, 0, 0, 67, 0, 0, 0, 0, 0, 0, 0, 197, 3, 0, 0, 67, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 66, 0, 0, 0, 15, 4, 0, 0, 1, 0, 0, 4, 8, 0, 0, 0, 192, 3, 0, 0, 69, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 106, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 8, 0, 0, 0, 26, 4, 0, 0, 72, 0, 0, 0, 0, 0, 0, 0, 33, 4, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 47, 4, 0, 0, 0, 0, 0, 8, 73, 0, 0, 0, 55, 4, 0, 0, 0, 0, 0, 8, 74, 0, 0, 0,
        59, 4, 0, 0, 0, 0, 0, 8, 51, 0, 0, 0, 65, 4, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 75, 0, 0, 0, 4, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        5, 16, 0, 0, 0, 0, 0, 0, 0, 78, 0, 0, 0, 0, 0, 0, 0, 70, 4, 0, 0, 66, 0, 0, 0, 0, 0, 0, 0,
        89, 4, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 99, 4, 0, 0, 11,
        0, 0, 0, 0, 0, 0, 0, 111, 4, 0, 0, 79, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 80, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0, 0, 28, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 60, 0, 0, 0, 0, 0,
        0, 0, 83, 0, 0, 0, 0, 0, 0, 0, 122, 4, 0, 0, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 0, 0,
        132, 60, 0, 0, 0, 130, 4, 0, 0, 81, 0, 0, 0, 0, 0, 0, 0, 148, 4, 0, 0, 28, 0, 0, 0, 0, 0,
        0, 3, 157, 4, 0, 0, 28, 0, 0, 0, 3, 0, 0, 1, 167, 4, 0, 0, 28, 0, 0, 0, 4, 0, 0, 1, 187, 4,
        0, 0, 28, 0, 0, 0, 5, 0, 0, 2, 197, 4, 0, 0, 28, 0, 0, 0, 7, 0, 0, 1, 206, 4, 0, 0, 81, 0,
        0, 0, 8, 0, 0, 0, 223, 4, 0, 0, 28, 0, 0, 0, 8, 0, 0, 2, 235, 4, 0, 0, 28, 0, 0, 0, 10, 0,
        0, 1, 249, 4, 0, 0, 28, 0, 0, 0, 11, 0, 0, 1, 10, 5, 0, 0, 28, 0, 0, 0, 12, 0, 0, 1, 26, 5,
        0, 0, 28, 0, 0, 0, 13, 0, 0, 1, 43, 5, 0, 0, 28, 0, 0, 0, 14, 0, 0, 2, 54, 5, 0, 0, 28, 0,
        0, 0, 16, 0, 0, 1, 74, 5, 0, 0, 28, 0, 0, 0, 17, 0, 0, 1, 82, 5, 0, 0, 28, 0, 0, 0, 18, 0,
        0, 1, 90, 5, 0, 0, 28, 0, 0, 0, 19, 0, 0, 1, 107, 5, 0, 0, 28, 0, 0, 0, 20, 0, 0, 1, 118,
        5, 0, 0, 28, 0, 0, 0, 21, 0, 0, 1, 125, 5, 0, 0, 28, 0, 0, 0, 22, 0, 0, 1, 139, 5, 0, 0,
        28, 0, 0, 0, 23, 0, 0, 1, 154, 5, 0, 0, 28, 0, 0, 0, 24, 0, 0, 1, 165, 5, 0, 0, 28, 0, 0,
        0, 25, 0, 0, 2, 180, 5, 0, 0, 28, 0, 0, 0, 27, 0, 0, 1, 194, 5, 0, 0, 28, 0, 0, 0, 28, 0,
        0, 1, 203, 5, 0, 0, 28, 0, 0, 0, 29, 0, 0, 1, 220, 5, 0, 0, 28, 0, 0, 0, 30, 0, 0, 1, 240,
        5, 0, 0, 28, 0, 0, 0, 31, 0, 0, 1, 251, 5, 0, 0, 28, 0, 0, 0, 32, 0, 0, 1, 8, 6, 0, 0, 28,
        0, 0, 0, 33, 0, 0, 1, 23, 6, 0, 0, 28, 0, 0, 0, 34, 0, 0, 1, 33, 6, 0, 0, 28, 0, 0, 0, 35,
        0, 0, 1, 42, 6, 0, 0, 28, 0, 0, 0, 36, 0, 0, 1, 56, 6, 0, 0, 28, 0, 0, 0, 37, 0, 0, 1, 67,
        6, 0, 0, 14, 0, 0, 0, 48, 0, 0, 0, 76, 6, 0, 0, 13, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 84,
        0, 0, 0, 96, 0, 0, 0, 86, 6, 0, 0, 86, 0, 0, 0, 128, 0, 0, 0, 95, 6, 0, 0, 2, 0, 0, 0, 160,
        0, 0, 0, 103, 6, 0, 0, 86, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 224, 0, 0, 0, 0,
        0, 0, 0, 92, 0, 0, 0, 0, 1, 0, 0, 108, 6, 0, 0, 86, 0, 0, 0, 32, 1, 0, 0, 0, 0, 0, 0, 93,
        0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 0, 94, 0, 0, 0, 96, 1, 0, 0, 116, 6, 0, 0, 14, 0, 0, 0, 112,
        1, 0, 0, 139, 6, 0, 0, 14, 0, 0, 0, 128, 1, 0, 0, 160, 6, 0, 0, 14, 0, 0, 0, 144, 1, 0, 0,
        177, 6, 0, 0, 91, 0, 0, 0, 160, 1, 0, 0, 186, 6, 0, 0, 14, 0, 0, 0, 176, 1, 0, 0, 203, 6,
        0, 0, 14, 0, 0, 0, 192, 1, 0, 0, 218, 6, 0, 0, 14, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 0, 2, 0,
        0, 5, 4, 0, 0, 0, 229, 6, 0, 0, 85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 87, 0, 0, 0, 0, 0, 0,
        0, 234, 6, 0, 0, 0, 0, 0, 8, 86, 0, 0, 0, 241, 6, 0, 0, 0, 0, 0, 8, 53, 0, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 4, 4, 0, 0, 0, 247, 6, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 2, 7, 0, 0, 14, 0, 0, 0,
        16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 4, 0, 0, 0, 14, 7, 0, 0, 89, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 0, 23, 7, 0, 0, 0, 0, 0, 8, 86, 0, 0, 0, 0, 0, 0, 0, 2, 0,
        0, 4, 4, 0, 0, 0, 27, 7, 0, 0, 91, 0, 0, 0, 0, 0, 0, 0, 38, 7, 0, 0, 14, 0, 0, 0, 16, 0, 0,
        0, 47, 7, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 4, 0, 0, 0, 54, 7, 0, 0,
        53, 0, 0, 0, 0, 0, 0, 0, 62, 7, 0, 0, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 4,
        0, 0, 0, 73, 7, 0, 0, 86, 0, 0, 0, 0, 0, 0, 0, 78, 7, 0, 0, 86, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 2, 0, 0, 0, 96, 7, 0, 0, 91, 0, 0, 0, 0, 0, 0, 0, 111, 7, 0, 0, 28, 0, 0,
        0, 0, 0, 0, 0, 125, 7, 0, 0, 0, 0, 0, 8, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 29, 0, 0, 0,
        140, 7, 0, 0, 0, 0, 0, 8, 98, 0, 0, 0, 151, 7, 0, 0, 1, 0, 0, 4, 4, 0, 0, 0, 167, 7, 0, 0,
        99, 0, 0, 0, 0, 0, 0, 0, 172, 7, 0, 0, 0, 0, 0, 8, 100, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 4, 4,
        0, 0, 0, 181, 7, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 112, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 75, 0, 0, 0, 4, 0, 0, 0,
        4, 0, 0, 0, 189, 7, 0, 0, 0, 0, 0, 14, 103, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        0, 0, 0, 75, 0, 0, 0, 4, 0, 0, 0, 8, 0, 0, 0, 197, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 90, 2,
        0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 202, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 210, 7, 0, 0, 0, 0, 0,
        7, 0, 0, 0, 0, 221, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 107, 2, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0,
        227, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 235, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 245, 7, 0, 0,
        0, 0, 0, 7, 0, 0, 0, 0, 138, 11, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 146, 11, 0, 0, 1, 0, 0, 15, 16, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0,
        0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69,
        95, 95, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0,
        101, 118, 101, 110, 116, 115, 0, 112, 116, 95, 114, 101, 103, 115, 0, 114, 49, 53, 0, 114,
        49, 52, 0, 114, 49, 51, 0, 114, 49, 50, 0, 98, 112, 0, 98, 120, 0, 114, 49, 49, 0, 114, 49,
        48, 0, 114, 57, 0, 114, 56, 0, 97, 120, 0, 99, 120, 0, 100, 120, 0, 115, 105, 0, 100, 105,
        0, 111, 114, 105, 103, 95, 97, 120, 0, 105, 112, 0, 102, 108, 97, 103, 115, 0, 115, 112, 0,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 0, 99, 115, 0, 99, 115,
        120, 0, 102, 114, 101, 100, 95, 99, 115, 0, 117, 49, 54, 0, 95, 95, 117, 49, 54, 0, 117,
        110, 115, 105, 103, 110, 101, 100, 32, 115, 104, 111, 114, 116, 0, 117, 54, 52, 0, 95, 95,
        117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108,
        111, 110, 103, 0, 115, 108, 0, 119, 102, 101, 0, 115, 115, 0, 115, 115, 120, 0, 102, 114,
        101, 100, 95, 115, 115, 0, 115, 116, 105, 0, 115, 119, 101, 118, 101, 110, 116, 0, 110,
        109, 105, 0, 118, 101, 99, 116, 111, 114, 0, 101, 110, 99, 108, 97, 118, 101, 0, 108, 0,
        110, 101, 115, 116, 101, 100, 0, 105, 110, 115, 110, 108, 101, 110, 0, 99, 116, 120, 0, 97,
        112, 105, 95, 115, 101, 110, 116, 105, 110, 101, 108, 0, 109, 115, 103, 104, 100, 114, 0,
        109, 115, 103, 95, 110, 97, 109, 101, 0, 109, 115, 103, 95, 110, 97, 109, 101, 108, 101,
        110, 0, 109, 115, 103, 95, 105, 110, 113, 0, 109, 115, 103, 95, 105, 116, 101, 114, 0, 109,
        115, 103, 95, 99, 111, 110, 116, 114, 111, 108, 95, 105, 115, 95, 117, 115, 101, 114, 0,
        109, 115, 103, 95, 103, 101, 116, 95, 105, 110, 113, 0, 109, 115, 103, 95, 102, 108, 97,
        103, 115, 0, 109, 115, 103, 95, 99, 111, 110, 116, 114, 111, 108, 108, 101, 110, 0, 109,
        115, 103, 95, 105, 111, 99, 98, 0, 109, 115, 103, 95, 117, 98, 117, 102, 0, 115, 103, 95,
        102, 114, 111, 109, 95, 105, 116, 101, 114, 0, 105, 111, 118, 95, 105, 116, 101, 114, 0,
        105, 116, 101, 114, 95, 116, 121, 112, 101, 0, 110, 111, 102, 97, 117, 108, 116, 0, 100,
        97, 116, 97, 95, 115, 111, 117, 114, 99, 101, 0, 105, 111, 118, 95, 111, 102, 102, 115,
        101, 116, 0, 117, 56, 0, 95, 95, 117, 56, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32,
        99, 104, 97, 114, 0, 98, 111, 111, 108, 0, 95, 66, 111, 111, 108, 0, 115, 105, 122, 101,
        95, 116, 0, 95, 95, 107, 101, 114, 110, 101, 108, 95, 115, 105, 122, 101, 95, 116, 0, 95,
        95, 107, 101, 114, 110, 101, 108, 95, 117, 108, 111, 110, 103, 95, 116, 0, 95, 95, 117, 98,
        117, 102, 95, 105, 111, 118, 101, 99, 0, 105, 111, 118, 101, 99, 0, 105, 111, 118, 95, 98,
        97, 115, 101, 0, 105, 111, 118, 95, 108, 101, 110, 0, 99, 111, 117, 110, 116, 0, 95, 95,
        105, 111, 118, 0, 107, 118, 101, 99, 0, 98, 118, 101, 99, 0, 102, 111, 108, 105, 111, 113,
        0, 120, 97, 114, 114, 97, 121, 0, 117, 98, 117, 102, 0, 110, 114, 95, 115, 101, 103, 115,
        0, 102, 111, 108, 105, 111, 113, 95, 115, 108, 111, 116, 0, 120, 97, 114, 114, 97, 121, 95,
        115, 116, 97, 114, 116, 0, 108, 111, 102, 102, 95, 116, 0, 95, 95, 107, 101, 114, 110, 101,
        108, 95, 108, 111, 102, 102, 95, 116, 0, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0,
        109, 115, 103, 95, 99, 111, 110, 116, 114, 111, 108, 0, 109, 115, 103, 95, 99, 111, 110,
        116, 114, 111, 108, 95, 117, 115, 101, 114, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32,
        105, 110, 116, 0, 115, 107, 95, 98, 117, 102, 102, 0, 115, 107, 0, 99, 98, 0, 95, 110, 102,
        99, 116, 0, 108, 101, 110, 0, 100, 97, 116, 97, 95, 108, 101, 110, 0, 109, 97, 99, 95, 108,
        101, 110, 0, 104, 100, 114, 95, 108, 101, 110, 0, 113, 117, 101, 117, 101, 95, 109, 97,
        112, 112, 105, 110, 103, 0, 95, 95, 99, 108, 111, 110, 101, 100, 95, 111, 102, 102, 115,
        101, 116, 0, 99, 108, 111, 110, 101, 100, 0, 110, 111, 104, 100, 114, 0, 102, 99, 108, 111,
        110, 101, 0, 112, 101, 101, 107, 101, 100, 0, 104, 101, 97, 100, 95, 102, 114, 97, 103, 0,
        112, 102, 109, 101, 109, 97, 108, 108, 111, 99, 0, 112, 112, 95, 114, 101, 99, 121, 99,
        108, 101, 0, 97, 99, 116, 105, 118, 101, 95, 101, 120, 116, 101, 110, 115, 105, 111, 110,
        115, 0, 116, 97, 105, 108, 0, 101, 110, 100, 0, 104, 101, 97, 100, 0, 100, 97, 116, 97, 0,
        116, 114, 117, 101, 115, 105, 122, 101, 0, 117, 115, 101, 114, 115, 0, 101, 120, 116, 101,
        110, 115, 105, 111, 110, 115, 0, 114, 98, 110, 111, 100, 101, 0, 108, 105, 115, 116, 0,
        108, 108, 95, 110, 111, 100, 101, 0, 110, 101, 120, 116, 0, 112, 114, 101, 118, 0, 100,
        101, 118, 0, 100, 101, 118, 95, 115, 99, 114, 97, 116, 99, 104, 0, 114, 98, 95, 110, 111,
        100, 101, 0, 95, 95, 114, 98, 95, 112, 97, 114, 101, 110, 116, 95, 99, 111, 108, 111, 114,
        0, 114, 98, 95, 114, 105, 103, 104, 116, 0, 114, 98, 95, 108, 101, 102, 116, 0, 108, 105,
        115, 116, 95, 104, 101, 97, 100, 0, 108, 108, 105, 115, 116, 95, 110, 111, 100, 101, 0,
        116, 115, 116, 97, 109, 112, 0, 115, 107, 98, 95, 109, 115, 116, 97, 109, 112, 95, 110,
        115, 0, 107, 116, 105, 109, 101, 95, 116, 0, 115, 54, 52, 0, 95, 95, 115, 54, 52, 0, 99,
        104, 97, 114, 0, 116, 99, 112, 95, 116, 115, 111, 114, 116, 101, 100, 95, 97, 110, 99, 104,
        111, 114, 0, 95, 115, 107, 95, 114, 101, 100, 105, 114, 0, 95, 115, 107, 98, 95, 114, 101,
        102, 100, 115, 116, 0, 100, 101, 115, 116, 114, 117, 99, 116, 111, 114, 0, 104, 101, 97,
        100, 101, 114, 115, 0, 95, 95, 112, 107, 116, 95, 116, 121, 112, 101, 95, 111, 102, 102,
        115, 101, 116, 0, 112, 107, 116, 95, 116, 121, 112, 101, 0, 105, 103, 110, 111, 114, 101,
        95, 100, 102, 0, 100, 115, 116, 95, 112, 101, 110, 100, 105, 110, 103, 95, 99, 111, 110,
        102, 105, 114, 109, 0, 105, 112, 95, 115, 117, 109, 109, 101, 100, 0, 111, 111, 111, 95,
        111, 107, 97, 121, 0, 95, 95, 109, 111, 110, 111, 95, 116, 99, 95, 111, 102, 102, 115, 101,
        116, 0, 116, 115, 116, 97, 109, 112, 95, 116, 121, 112, 101, 0, 116, 99, 95, 97, 116, 95,
        105, 110, 103, 114, 101, 115, 115, 0, 116, 99, 95, 115, 107, 105, 112, 95, 99, 108, 97,
        115, 115, 105, 102, 121, 0, 114, 101, 109, 99, 115, 117, 109, 95, 111, 102, 102, 108, 111,
        97, 100, 0, 99, 115, 117, 109, 95, 99, 111, 109, 112, 108, 101, 116, 101, 95, 115, 119, 0,
        99, 115, 117, 109, 95, 108, 101, 118, 101, 108, 0, 105, 110, 110, 101, 114, 95, 112, 114,
        111, 116, 111, 99, 111, 108, 95, 116, 121, 112, 101, 0, 108, 52, 95, 104, 97, 115, 104, 0,
        115, 119, 95, 104, 97, 115, 104, 0, 119, 105, 102, 105, 95, 97, 99, 107, 101, 100, 95, 118,
        97, 108, 105, 100, 0, 119, 105, 102, 105, 95, 97, 99, 107, 101, 100, 0, 110, 111, 95, 102,
        99, 115, 0, 101, 110, 99, 97, 112, 115, 117, 108, 97, 116, 105, 111, 110, 0, 101, 110, 99,
        97, 112, 95, 104, 100, 114, 95, 99, 115, 117, 109, 0, 99, 115, 117, 109, 95, 118, 97, 108,
        105, 100, 0, 110, 100, 105, 115, 99, 95, 110, 111, 100, 101, 116, 121, 112, 101, 0, 105,
        112, 118, 115, 95, 112, 114, 111, 112, 101, 114, 116, 121, 0, 110, 102, 95, 116, 114, 97,
        99, 101, 0, 111, 102, 102, 108, 111, 97, 100, 95, 102, 119, 100, 95, 109, 97, 114, 107, 0,
        111, 102, 102, 108, 111, 97, 100, 95, 108, 51, 95, 102, 119, 100, 95, 109, 97, 114, 107, 0,
        114, 101, 100, 105, 114, 101, 99, 116, 101, 100, 0, 102, 114, 111, 109, 95, 105, 110, 103,
        114, 101, 115, 115, 0, 110, 102, 95, 115, 107, 105, 112, 95, 101, 103, 114, 101, 115, 115,
        0, 100, 101, 99, 114, 121, 112, 116, 101, 100, 0, 115, 108, 111, 119, 95, 103, 114, 111, 0,
        99, 115, 117, 109, 95, 110, 111, 116, 95, 105, 110, 101, 116, 0, 117, 110, 114, 101, 97,
        100, 97, 98, 108, 101, 0, 116, 99, 95, 105, 110, 100, 101, 120, 0, 97, 108, 108, 111, 99,
        95, 99, 112, 117, 0, 112, 114, 105, 111, 114, 105, 116, 121, 0, 115, 107, 98, 95, 105, 105,
        102, 0, 104, 97, 115, 104, 0, 115, 101, 99, 109, 97, 114, 107, 0, 105, 110, 110, 101, 114,
        95, 116, 114, 97, 110, 115, 112, 111, 114, 116, 95, 104, 101, 97, 100, 101, 114, 0, 105,
        110, 110, 101, 114, 95, 110, 101, 116, 119, 111, 114, 107, 95, 104, 101, 97, 100, 101, 114,
        0, 105, 110, 110, 101, 114, 95, 109, 97, 99, 95, 104, 101, 97, 100, 101, 114, 0, 112, 114,
        111, 116, 111, 99, 111, 108, 0, 116, 114, 97, 110, 115, 112, 111, 114, 116, 95, 104, 101,
        97, 100, 101, 114, 0, 110, 101, 116, 119, 111, 114, 107, 95, 104, 101, 97, 100, 101, 114,
        0, 109, 97, 99, 95, 104, 101, 97, 100, 101, 114, 0, 99, 115, 117, 109, 0, 95, 95, 119, 115,
        117, 109, 0, 95, 95, 117, 51, 50, 0, 99, 115, 117, 109, 95, 115, 116, 97, 114, 116, 0, 99,
        115, 117, 109, 95, 111, 102, 102, 115, 101, 116, 0, 118, 108, 97, 110, 95, 97, 108, 108, 0,
        117, 51, 50, 0, 118, 108, 97, 110, 95, 112, 114, 111, 116, 111, 0, 118, 108, 97, 110, 95,
        116, 99, 105, 0, 95, 95, 98, 101, 49, 54, 0, 110, 97, 112, 105, 95, 105, 100, 0, 115, 101,
        110, 100, 101, 114, 95, 99, 112, 117, 0, 109, 97, 114, 107, 0, 114, 101, 115, 101, 114,
        118, 101, 100, 95, 116, 97, 105, 108, 114, 111, 111, 109, 0, 105, 110, 110, 101, 114, 95,
        112, 114, 111, 116, 111, 99, 111, 108, 0, 105, 110, 110, 101, 114, 95, 105, 112, 112, 114,
        111, 116, 111, 0, 115, 107, 95, 98, 117, 102, 102, 95, 100, 97, 116, 97, 95, 116, 0, 114,
        101, 102, 99, 111, 117, 110, 116, 95, 116, 0, 114, 101, 102, 99, 111, 117, 110, 116, 95,
        115, 116, 114, 117, 99, 116, 0, 114, 101, 102, 115, 0, 97, 116, 111, 109, 105, 99, 95, 116,
        0, 99, 111, 117, 110, 116, 101, 114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 115, 111, 99, 107,
        0, 98, 105, 111, 95, 118, 101, 99, 0, 110, 101, 116, 95, 100, 101, 118, 105, 99, 101, 0,
        107, 105, 111, 99, 98, 0, 115, 107, 98, 95, 101, 120, 116, 0, 117, 98, 117, 102, 95, 105,
        110, 102, 111, 0, 102, 111, 108, 105, 111, 95, 113, 117, 101, 117, 101, 0, 47, 104, 111,
        109, 101, 47, 114, 111, 104, 105, 116, 104, 97, 107, 117, 108, 97, 47, 65, 120, 108, 101,
        114, 111, 47, 65, 80, 73, 45, 83, 101, 110, 116, 105, 110, 101, 108, 47, 101, 98, 112, 102,
        47, 97, 112, 105, 45, 115, 101, 110, 116, 105, 110, 101, 108, 45, 108, 105, 98, 98, 112,
        102, 47, 115, 114, 99, 47, 98, 112, 102, 47, 97, 112, 105, 95, 115, 101, 110, 116, 105,
        110, 101, 108, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 80, 82,
        79, 66, 69, 40, 97, 112, 105, 95, 115, 101, 110, 116, 105, 110, 101, 108, 44, 0, 32, 32,
        32, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 99, 111,
        109, 109, 40, 99, 111, 109, 109, 44, 32, 115, 105, 122, 101, 111, 102, 40, 99, 111, 109,
        109, 41, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 95, 95, 98, 117, 105, 108, 116, 105,
        110, 95, 109, 101, 109, 99, 109, 112, 40, 99, 111, 109, 109, 44, 32, 34, 117, 118, 105, 99,
        111, 114, 110, 34, 44, 32, 55, 41, 32, 33, 61, 32, 48, 41, 0, 32, 32, 32, 32, 115, 116,
        114, 117, 99, 116, 32, 101, 118, 101, 110, 116, 32, 42, 101, 32, 61, 32, 98, 112, 102, 95,
        114, 105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40, 38, 101, 118,
        101, 110, 116, 115, 44, 32, 115, 105, 122, 101, 111, 102, 40, 42, 101, 41, 44, 32, 48, 41,
        59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 33, 101, 41, 0, 32, 32, 32, 32, 101, 45, 62, 116,
        115, 32, 61, 32, 98, 112, 102, 95, 107, 116, 105, 109, 101, 95, 103, 101, 116, 95, 110,
        115, 40, 41, 59, 0, 32, 32, 32, 32, 101, 45, 62, 112, 105, 100, 32, 61, 32, 98, 112, 102,
        95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 112, 105, 100, 95, 116, 103,
        105, 100, 40, 41, 32, 62, 62, 32, 51, 50, 59, 0, 32, 32, 32, 32, 95, 95, 98, 117, 105, 108,
        116, 105, 110, 95, 109, 101, 109, 99, 112, 121, 40, 101, 45, 62, 99, 111, 109, 109, 44, 32,
        99, 111, 109, 109, 44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 45, 62, 99, 111, 109,
        109, 41, 41, 59, 0, 32, 32, 32, 32, 95, 95, 98, 117, 105, 108, 116, 105, 110, 95, 109, 101,
        109, 115, 101, 116, 40, 101, 45, 62, 100, 97, 116, 97, 44, 32, 48, 44, 32, 115, 105, 122,
        101, 111, 102, 40, 101, 45, 62, 100, 97, 116, 97, 41, 41, 59, 0, 32, 32, 32, 32, 101, 45,
        62, 108, 101, 110, 32, 61, 32, 48, 59, 0, 32, 32, 32, 32, 115, 116, 114, 117, 99, 116, 32,
        105, 111, 118, 95, 105, 116, 101, 114, 32, 105, 116, 101, 114, 32, 61, 32, 123, 125, 59, 0,
        32, 32, 32, 32, 105, 102, 32, 40, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101,
        97, 100, 95, 107, 101, 114, 110, 101, 108, 40, 38, 105, 116, 101, 114, 44, 32, 115, 105,
        122, 101, 111, 102, 40, 105, 116, 101, 114, 41, 44, 32, 38, 109, 115, 103, 45, 62, 109,
        115, 103, 95, 105, 116, 101, 114, 41, 32, 61, 61, 32, 48, 41, 32, 123, 0, 32, 32, 32, 32,
        32, 32, 32, 32, 105, 102, 32, 40, 105, 116, 101, 114, 46, 117, 98, 117, 102, 32, 38, 38,
        32, 105, 116, 101, 114, 46, 99, 111, 117, 110, 116, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 117, 51, 50, 32, 99, 111, 112, 121, 95, 108, 101, 110, 32, 61, 32,
        40, 117, 51, 50, 41, 105, 116, 101, 114, 46, 99, 111, 117, 110, 116, 59, 0, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 112, 121, 95, 108, 101, 110, 32, 38, 61, 32, 48,
        120, 102, 102, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 105, 102, 32, 40, 99,
        111, 112, 121, 95, 108, 101, 110, 32, 62, 32, 48, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 101, 45, 62, 108, 101, 110, 32, 61, 32, 99, 111,
        112, 121, 95, 108, 101, 110, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101,
        114, 40, 101, 45, 62, 100, 97, 116, 97, 44, 32, 99, 111, 112, 121, 95, 108, 101, 110, 44,
        32, 105, 116, 101, 114, 46, 117, 98, 117, 102, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95,
        114, 105, 110, 103, 98, 117, 102, 95, 115, 117, 98, 109, 105, 116, 40, 101, 44, 32, 48, 41,
        59, 0, 48, 58, 49, 51, 0, 48, 58, 51, 0, 48, 58, 52, 58, 49, 58, 48, 58, 53, 0, 48, 58, 52,
        58, 49, 58, 49, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 107, 112,
        114, 111, 98, 101, 47, 116, 99, 112, 95, 115, 101, 110, 100, 109, 115, 103, 95, 108, 111,
        99, 107, 101, 100, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0,
        0, 220, 1, 0, 0, 240, 1, 0, 0, 108, 0, 0, 0, 8, 0, 0, 0, 152, 11, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 23, 0, 0, 0, 16, 0, 0, 0, 152, 11, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 91, 8,
        0, 0, 5, 88, 0, 0, 24, 0, 0, 0, 1, 8, 0, 0, 120, 8, 0, 0, 5, 116, 0, 0, 40, 0, 0, 0, 1, 8,
        0, 0, 166, 8, 0, 0, 9, 124, 0, 0, 208, 0, 0, 0, 1, 8, 0, 0, 166, 8, 0, 0, 46, 124, 0, 0,
        224, 0, 0, 0, 1, 8, 0, 0, 217, 8, 0, 0, 23, 136, 0, 0, 16, 1, 0, 0, 1, 8, 0, 0, 28, 9, 0,
        0, 9, 140, 0, 0, 24, 1, 0, 0, 1, 8, 0, 0, 40, 9, 0, 0, 13, 152, 0, 0, 32, 1, 0, 0, 1, 8, 0,
        0, 40, 9, 0, 0, 11, 152, 0, 0, 40, 1, 0, 0, 1, 8, 0, 0, 72, 9, 0, 0, 14, 156, 0, 0, 48, 1,
        0, 0, 1, 8, 0, 0, 72, 9, 0, 0, 41, 156, 0, 0, 56, 1, 0, 0, 1, 8, 0, 0, 72, 9, 0, 0, 12,
        156, 0, 0, 64, 1, 0, 0, 1, 8, 0, 0, 119, 9, 0, 0, 5, 164, 0, 0, 64, 2, 0, 0, 1, 8, 0, 0,
        173, 9, 0, 0, 5, 168, 0, 0, 72, 3, 0, 0, 1, 8, 0, 0, 224, 9, 0, 0, 12, 172, 0, 0, 80, 3, 0,
        0, 1, 8, 0, 0, 240, 9, 0, 0, 21, 180, 0, 0, 152, 3, 0, 0, 1, 8, 0, 0, 15, 10, 0, 0, 9, 188,
        0, 0, 176, 3, 0, 0, 1, 8, 0, 0, 15, 10, 0, 0, 68, 188, 0, 0, 200, 3, 0, 0, 1, 8, 0, 0, 90,
        10, 0, 0, 18, 196, 0, 0, 208, 3, 0, 0, 1, 8, 0, 0, 90, 10, 0, 0, 23, 196, 0, 0, 232, 3, 0,
        0, 1, 8, 0, 0, 90, 10, 0, 0, 31, 196, 0, 0, 240, 3, 0, 0, 1, 8, 0, 0, 90, 10, 0, 0, 23,
        196, 0, 0, 248, 3, 0, 0, 1, 8, 0, 0, 129, 10, 0, 0, 38, 208, 0, 0, 0, 4, 0, 0, 1, 8, 0, 0,
        173, 10, 0, 0, 22, 212, 0, 0, 8, 4, 0, 0, 1, 8, 0, 0, 203, 10, 0, 0, 26, 232, 0, 0, 32, 4,
        0, 0, 1, 8, 0, 0, 235, 10, 0, 0, 24, 236, 0, 0, 40, 4, 0, 0, 1, 8, 0, 0, 14, 11, 0, 0, 61,
        240, 0, 0, 48, 4, 0, 0, 1, 8, 0, 0, 14, 11, 0, 0, 17, 240, 0, 0, 56, 4, 0, 0, 1, 8, 0, 0,
        81, 11, 0, 0, 5, 4, 1, 0, 80, 4, 0, 0, 1, 8, 0, 0, 91, 8, 0, 0, 5, 88, 0, 0, 16, 0, 0, 0,
        152, 11, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 111, 11, 0, 0, 0, 0, 0, 0, 120, 3, 0,
        0, 24, 0, 0, 0, 116, 11, 0, 0, 0, 0, 0, 0, 200, 3, 0, 0, 26, 0, 0, 0, 120, 11, 0, 0, 0, 0,
        0, 0, 232, 3, 0, 0, 26, 0, 0, 0, 130, 11, 0, 0, 0, 0, 0, 0, 248, 3, 0, 0, 26, 0, 0, 0, 130,
        11, 0, 0, 0, 0, 0, 0, 40, 4, 0, 0, 26, 0, 0, 0, 120, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 163, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 232, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 144, 1, 0, 0, 0, 0, 0, 0, 96, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 5, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 1, 0, 0, 0, 3,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 5, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0,
        1, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 6, 0, 0, 0, 0, 0, 0, 8, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        119, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 6, 0, 0, 0,
        0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 149, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        32, 6, 0, 0, 0, 0, 0, 0, 46, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 154, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 80, 33, 0, 0, 0, 0, 0, 0, 124, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
